name: Upload to S3
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: chrislennon/action-aws-cli@v1.1
        with:
          node-version: 10.x
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      - run: yarn install
      - run: yarn build
      - run: aws s3 sync dist/ s3://www.m5a.jp --delete
